import { ENROLLMENT_STATUS } from "../../types/serviceUsers";

export const allEnrollmentStatuses = [
  ENROLLMENT_STATUS.LIVE,
  ENROLLMENT_STATUS.PRE_ADMISSION,
  ENROLLMENT_STATUS.ARCHIVED,
  ENROLLMENT_STATUS.Hospitalized,
  ENROLLMENT_STATUS.ON_HOLD,
  ENROLLMENT_STATUS.ARCHIVED_PRE_ADMISSION,
];
